### ISSUE TITLE
mimic_animations [ stop sending attack packets if the unit is walking ]

### ISSUE THREAD

**Issue by AcidMarco** [csnv/hercules-plugins#2]
If AfterCastWalkDelay value in skilldb for AS_SONICBLOW / CG_ARROWVULCAN skills is low (ex. 500 ms), the unit may walk when the attack-animation loop is not finished yet. In this way the client may show attacks in different direction.

I offer forcibly stop sending attack packets, if the unit is walking. 

**function : use_animation**

if ( unit->is_walking(bl) ) {
	clear_timer(bl, true);
	return 0;
	}

**Comment by csnv** [comment]
Reproducing the animation even if the character moves is/was the normal behavior back then when the animation was in place. I've pushed a small update that fixes the wrong facing direction, but the attacking animation will be kept when moving.
